name: ecommerce_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons:
  flutter_screenutil: ^5.8.4 
  shared_preferences: ^2.2.0 
  flutter_launcher_icons: 
  change_app_package_name: ^1.5.0 
  rename_app: 
  flutter_svg: ^2.0.17
  flutter_animate: 
  get:
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  uuid: ^3.0.0
  image_picker: ^1.1.2
  intl: any
  flutter: 
    sdk: flutter

dev_dependencies:
  mockito:
  flutter_lints:

  integration_test:
    sdk: flutter

  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  adaptive_icon_bakground: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  image_path: "assets/images/app_icon.png"
flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700

    - family: StickyFont
      fonts:
        - asset: assets/fonts/Pinky-Show.ttf

